// <auto-generated />
using System;
using ListaTarefas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ListaTarefas.Data.Migrations
{
    [DbContext(typeof(ListaTarefasContext))]
    [Migration("20240423204852_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ListaTarefas.Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<bool>("Completa")
                        .HasColumnType("bit(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("completa");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("datafim");

                    b.Property<DateTime?>("DataInicio")
                        .IsRequired()
                        .HasColumnType("date")
                        .HasColumnName("datainicio");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("datavencimento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("titulo");

                    b.HasKey("Id");

                    b.ToTable("tarefa");
                });

            modelBuilder.Entity("ListaTarefas.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("usuario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "root",
                            Password = "1234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
