// <auto-generated />
using System;
using ListaTarefas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ListaTarefas.Data.Migrations
{
    [DbContext(typeof(ListaTarefasContext))]
    [Migration("20240419194633_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ListaTarefas.Domain.Entities.Tarefa", b =>
                {
                    b.Property<int>("TarefaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("tarefaid");

                    b.Property<bool>("TarefaCompleta")
                        .HasColumnType("bit(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("tarefacompleta");

                    b.Property<DateTime?>("TarefaDataFim")
                        .HasColumnType("date")
                        .HasColumnName("tarefadtfim");

                    b.Property<DateTime?>("TarefaDataInicio")
                        .HasColumnType("date")
                        .HasColumnName("tarefadtinico");

                    b.Property<DateTime?>("TarefaDataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("tarefadtvenc");

                    b.Property<string>("TarefaDescricao")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tarefadescricao");

                    b.Property<string>("TarefaTitulo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("tarefatitulo");

                    b.HasKey("TarefaId");

                    b.ToTable("tarefa");
                });
#pragma warning restore 612, 618
        }
    }
}
